### ISSUE TITLE
신규 업데이트한 웹사이트 때문에 이메일 로고 및 이미지가 깨져나옴

### ISSUE THREAD

**Issue by yoonjs2** [cabbit-kanizsalab/cabbit-kanizsalab.github.io#29]
@ruunak 님 아래 리소스들이 누락되서 이메일 이미지가 깨져 나옵니다. 
과거 호환성을 위해서 누락된 이미지 추가를 부탁드립니다.

https://cabbit.io/images/Logo@#x.png
https://cabbit.io/images/ServiceGuide.gif

**Comment by ruunak** [comment]
@yoonjs2 누락된 이미지 추가했습니다. 리포팅 감사합니다!
